version: "3.7"

services:
  load-balancer:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs/ca.crt:/etc/nginx/ssl/ca.crt
      - ./certs/server.crt:/etc/nginx/ssl/server.crt
      - ./certs/server.key:/etc/nginx/ssl/server.key

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000